apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: dGVzdDEuY3ZxbWM4MDRlcjE4LmFwLXNvdXRoLTEucmRzLmFtYXpvbmF3cy5jb20=
  db_username: YWRtaW4=
  db_password: bWo3ODZkZWNjYW4=

