apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: dGVzdC5jdnFtYzgwNGVyMTguYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ==
  db_username: YWRtaW4=
  db_password: bWo3ODZkZWNjYW4=

